"use client";

import { useState } from "react";

import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

// import type { Metadata } from "next";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import "./globals.css";

//components
import { CssBaseline, ThemeProvider } from "@mui/material";
import { ColorModeContext, useMode } from "src/theme";
import Sidebar from "./global/Sidebar";
import Topbar from "./global/Topbar";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [theme, colorMode] = useMode();
  const [isSidebar, setIsSidebar] = useState<boolean>(true);

  return (
    <html lang="en">
      <body className={inter.className}>
        <ColorModeContext.Provider value={colorMode}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <div className="w-full h-full flex">
              <Sidebar isSidebar={isSidebar} />
              <main className="flex-1">
                <Topbar setIsSidebar={setIsSidebar} />
                {children}
              </main>
            </div>
          </ThemeProvider>
        </ColorModeContext.Provider>
      </body>
    </html>
  );
}
